sudo: required
dist: trusty
before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.1/bin/travis_setup.sh | bash -x
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

language: scala

scala:
  - "2.10.6"
  - "2.11.11"
  - "2.12.2"
  - "2.13.0-M1"

env:
  - SCALAJS_VERSION=0.6.18
  - SCALAJS_VERSION=1.0.0-M1

jdk:
  - oraclejdk8

script:
  # plz is like ++ except it skips projects that are not defined for that scala version.
  - sbt "plz $TRAVIS_SCALA_VERSION test mima-report-binary-issues"

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +
